In [2]:
!pip install -U spacy==3.*
!python -m spacy download en_core_web_sm
!python -m spacy info

     ---------------------------------------- 12.1/12.1 MB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 3.4 MB/s eta 0:00:00
     ---------------------------------------- 46.0/46.0 kB 2.4 MB/s eta 0:00:00
     -------------------------------------- 481.9/481.9 kB 3.8 MB/s eta 0:00:00
     -------------------------------------- 394.9/394.9 kB 2.5 MB/s eta 0:00:00
     ---------------------------------------- 50.1/50.1 kB 1.3 MB/s eta 0:00:00
     -------------------------------------- 181.6/181.6 kB 1.4 MB/s eta 0:00:00
     -------------------------------------- 122.2/122.2 kB 2.4 MB/s eta 0:00:00
     ---------------------------------------- 1.9/1.9 MB 1.1 MB/s eta 0:00:00
     ---------------------------------------- 6.6/6.6 MB 2.4 MB/s eta 0:00:00
     ---------------------------------------- 45.0/45.0 kB 1.1 MB/s eta 0:00:00
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_ext


============================== Info about spaCy ==============================

spaCy version    3.7.4                         
Location         C:\Users\kotaa\anaconda3\lib\site-packages\spacy
Platform         Windows-10-10.0.22621-SP0     
Python version   3.10.9                        
Pipelines        en_core_web_sm (3.7.1)        



In [4]:
!pip install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates from a subpr

In [6]:
import spacy

from scipy import spatial
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
corpus = [
    "Red Bull drops hint on F1 engine.",
    "Honda exits F1. leaving F1 partner Red Bull.",
    "Hemilton eyes record eighth F1 title.",
    "Aston Martin announces sponsor.",
]

In [9]:
vectorizer = CountVectorizer()

In [10]:
bow = vectorizer.fit_transform(corpus)

In [11]:
bow

<4x20 sparse matrix of type '<class 'numpy.int64'>'
	with 24 stored elements in Compressed Sparse Row format>

In [14]:
print(vectorizer.get_feature_names_out())

vectorizer.vocabulary_

['announces' 'aston' 'bull' 'drops' 'eighth' 'engine' 'exits' 'eyes' 'f1'
 'hemilton' 'hint' 'honda' 'leaving' 'martin' 'on' 'partner' 'record'
 'red' 'sponsor' 'title']


{'red': 17,
 'bull': 2,
 'drops': 3,
 'hint': 10,
 'on': 14,
 'f1': 8,
 'engine': 5,
 'honda': 11,
 'exits': 6,
 'leaving': 12,
 'partner': 15,
 'hemilton': 9,
 'eyes': 7,
 'record': 16,
 'eighth': 4,
 'title': 19,
 'aston': 1,
 'martin': 13,
 'announces': 0,
 'sponsor': 18}

In [15]:
print(bow)

  (0, 17)	1
  (0, 2)	1
  (0, 3)	1
  (0, 10)	1
  (0, 14)	1
  (0, 8)	1
  (0, 5)	1
  (1, 17)	1
  (1, 2)	1
  (1, 8)	2
  (1, 11)	1
  (1, 6)	1
  (1, 12)	1
  (1, 15)	1
  (2, 8)	1
  (2, 9)	1
  (2, 7)	1
  (2, 16)	1
  (2, 4)	1
  (2, 19)	1
  (3, 1)	1
  (3, 13)	1
  (3, 0)	1
  (3, 18)	1


In [21]:
nlp = spacy.load('en_core_web_sm')

def spacy_tokenizer(doc):
    return [t.text for t in nlp(doc) if not t.is_punct]

In [22]:
vectorizer = CountVectorizer(tokenizer = spacy_tokenizer, lowercase = False, binary = True)
bow = vectorizer.fit_transform(corpus)

In [23]:
print(vectorizer.get_feature_names_out())

vectorizer.vocabulary_

['Aston' 'Bull' 'F1' 'Hemilton' 'Honda' 'Martin' 'Red' 'announces' 'drops'
 'eighth' 'engine' 'exits' 'eyes' 'hint' 'leaving' 'on' 'partner' 'record'
 'sponsor' 'title']


{'Red': 6,
 'Bull': 1,
 'drops': 8,
 'hint': 13,
 'on': 15,
 'F1': 2,
 'engine': 10,
 'Honda': 4,
 'exits': 11,
 'leaving': 14,
 'partner': 16,
 'Hemilton': 3,
 'eyes': 12,
 'record': 17,
 'eighth': 9,
 'title': 19,
 'Aston': 0,
 'Martin': 5,
 'announces': 7,
 'sponsor': 18}

In [27]:
print(bow.toarray())
print()
print(bow)

[[0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0]
 [0 1 1 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0]
 [0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0]]

  (0, 6)	1
  (0, 1)	1
  (0, 8)	1
  (0, 13)	1
  (0, 15)	1
  (0, 2)	1
  (0, 10)	1
  (1, 6)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (1, 11)	1
  (1, 14)	1
  (1, 16)	1
  (2, 2)	1
  (2, 3)	1
  (2, 12)	1
  (2, 17)	1
  (2, 9)	1
  (2, 19)	1
  (3, 0)	1
  (3, 5)	1
  (3, 7)	1
  (3, 18)	1


# cosine

In [28]:
doc1_vs_doc2 = 1 - spatial.distance.cosine(bow[0].toarray(), bow[1].toarray())
doc1_vs_doc3 = 1 - spatial.distance.cosine(bow[0].toarray(), bow[2].toarray())
doc1_vs_doc4 = 1 - spatial.distance.cosine(bow[0].toarray(), bow[3].toarray())

print(corpus)

ValueError: Input vector should be 1-D.

In [29]:
print(cosine_similarity(bow))

[[1.         0.42857143 0.15430335 0.        ]
 [0.42857143 1.         0.15430335 0.        ]
 [0.15430335 0.15430335 1.         0.        ]
 [0.         0.         0.         1.        ]]
